# Generated by Django 2.2.7 on 2019-11-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='title',
        ),
    ]
