# Generated by Django 2.2.7 on 2019-11-22 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_remove_ebook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
